
name: CI

on:
  push:
  pull_request:

jobs:
  conda:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install conda
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/conda-ci/master/conda-ci
        source ./conda-ci install
        source ./conda-ci install-conda-build
    - name: Build
      run: |
        source activate base
        export CPU_COUNT=2
        conda-build -c conda-forge recipe
    - name: Install gpgpu-sim
      run: |
        source activate base
        conda install cudatoolkit-dev
        sudo apt-get install build-essential xutils-dev bison zlib1g-dev flex libglu1-mesa-dev
        wget https://github.com/gpgpu-sim/gpgpu-sim_distribution/archive/v4.0.1.tar.gz
        tar xzf v4.0.1.tar.gz
        cd gpgpu-sim_distribution-4.0.1
        source setup_environment release
        make
        conda install -c local cudamat
        python -c 'import cudamat'
        
